[package]
name = "tracelogs"
version = "0.2.0"
authors = ["sebastian <sebsch@geblubber.org>"]
edition = "2018"

[dependencies]
tokio = { version = "1.4.0", features = ["full"] }
log = "0.4"
simple_logger = "1.11.0"
regex = { version = "1"}

