---
targets:
  journald:
    - name: cron.service
      host: localhost
    - name: NetworkManager.service
      host: localhost
    - name: cron.service
      host: ssh://KEPPLER.nextcloud
  kubectl:
    - name: testrunner
      regex:
        datetime: 'r"[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1]) (2[0-3]|[01][0-9]):[0-5][0-9]:[0-5][0-9],[0-9][0-9][0-9]"'
        host: 'r"([^\s]+)"'
        service: 'r"([^\s]+)"'
        message: 'r"(.*)"'
        log_pattern:  'r"(?P<datetime>({d})) (?P<hostname>({h}))] (?P<service>({s})) (?P<message>({m}))"'
      date_string: "%Y-%m-%d %H:%M:%S,%f"